name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: read
  packages: read

jobs:
  Agroshop-contracts-validate:
    name: Run Agroshop-contracts release
    secrets: inherit
    uses: ./.github/workflows/Agroshop-contracts-ci.yaml

  Agroshop-contracts-release:
    name: Run Agroshop-contracts release
    secrets: inherit
    uses: ./.github/workflows/Agroshop-contracts-cd.yaml
    needs: Agroshop-contracts-validate

  Agroshop-frontend-validate:
    name: Run Agroshop-frontend release
    secrets: inherit
    uses: ./.github/workflows/Agroshop-frontend-ci.yaml

  Agroshop-frontend-release:
    name: Run Agroshop-frontend release
    secrets: inherit
    uses: ./.github/workflows/Agroshop-frontend-cd.yaml
    needs: Agroshop-frontend-validate
