name: Pull Request validation

on: [pull_request]


jobs:
  Agroshop-contracts-ci:
    name: Run Agroshop-contracts validation
    uses: ./.github/workflows/Agroshop-contracts-ci.yaml

  Agroshop-frontend-ci:
    name: Run Agroshop-frontend validation
    uses: ./.github/workflows/Agroshop-frontend-ci.yaml

